### ISSUE TITLE
MVVM Source Generators: Renaming certain names caught by generators fails.

### ISSUE THREAD

**Issue by Rosuavio** [CommunityToolkit/dotnet#17]
## Describe the bug
This might belong somewhere else but somewhere here might be able to help me find out the source of the issue.

Trying to rename a member var or its type that has the `ObservablePropertyAttribute` on it or rename a method name or the type of its parameter that has the `ICommandAttribute` on it the rename operation fails with an error.

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce

- [ ] Can this be reproduced in the Sample App? (Either in a sample as-is or with new XAML pasted in the editor.) If so, please provide custom XAML or steps to reproduce. If not, let us know why it can't be reproduced (e.g. more complex setup, environment, dependencies, etc...)

1. Given this code
```CS
    public struct Foo { int a; }
    public struct Faa { int a; }

    [ObservableObject]
    public class TestViewModel
    {
        [ObservableProperty]
        private Foo bar;

        [ICommand]
        private void DoBiz(Faa a) { }
    }
```
2. Try to rename `Foo`, `Faa`, `bar` or `DoBiz` using visual studio's rename functionality (Commonly bound to Ctrl+R, Ctrl+R)
3. See the rename dialog stuck with the "Searching..." text and no count of the amount of occurrences of the rename target.
4. Change the rename target's name.
5. Hit "Apply" on the rename dialog.
6. See visual studio error message.

## Expected behavior
Able to rename regardless if the name is captured in a source generator.

## Environment

NuGet Package(s): 

Package Version(s):

Windows 10 Build Number:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Insider Build ({build_number})

App min and target version:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Insider Build ({build_number})

Device form factor:

- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio version:

- [ ] 2017 (15.{minor_version})
- [x] 2019 (16.11.2)
- [ ] 2022 (17.{minor_version})

## Additional context

The stack trace from the error message

```
System.InvalidOperationException : The solution does not contain the specified document.
   at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.GetRequiredDocument(Solution solution,DocumentId documentId)
   at async Microsoft.CodeAnalysis.Rename.SerializableRenameLocation.RehydrateAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Rename.SerializableSearchResult.RehydrateAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Rename.RenameLocations.TryRehydrateAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Rename.RenameLocations.FindLocationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.AbstractEditorInlineRenameService.SymbolInlineRenameInfo.FindRenameLocationsAsync(<Unknown Parameters>)
   at async Microsoft.VisualStudio.Threading.JoinableTask.JoinAsync(<Unknown Parameters>)
   at async Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>g__JoinSlowAsync|3_0[T](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.<>c__DisplayClass39_0.<UpdateReferenceLocationsTask>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.<>c__DisplayClass69_0.<UpdateConflictResolutionTask>b__0(<Unknown Parameters>)
   at Microsoft.VisualStudio.Threading.JoinableTask.Join(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.Join(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.CommitCore(IWaitContext waitContext,Boolean previewChanges)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.<>c__DisplayClass78_0.<CommitWorker>b__0(IWaitContext waitContext)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.VisualStudioWaitIndicator.Wait(String title,String message,Boolean allowCancel,Boolean showProgress,Action`1 action)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.CommitWorker(Boolean previewChanges)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.Dashboard.Commit()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Sergio0694** [comment]
Transferred this just for tracking, but closing this as it's an issue with Roslyn.
We might want to write down a small repro or at least open an issue there if there isn't one already 👍
