### ISSUE TITLE
Stack trace does not give line number of offending code

### ISSUE THREAD

**Issue by sam-wheat** [CommunityToolkit/dotnet#282]
### Describe the bug

`RelayCommand<T>`  will fail if `T` is an incorrect type.  The stack trace does not provide the line number where the code fails or any other diagnostic information such as name of the command.

The stack trace below is exactly what is produced by the example program I have provided.

You will note the provided example fails to display the main window and allow the user to provide input.  It is not clear to me why `CommandParameter` is parsed prior to the user actually executing the command.

`at CommunityToolkit.Mvvm.Input.RelayCommand1.CanExecute(Object parameter)` is interesting... no delegate is provided IDK why this would attemt to execute.

	System.InvalidCastException
	  HResult=0x80004002
	  Message=Unable to cast object of type 'System.String' to type 'System.Int32'.
	  Source=System.Private.CoreLib
	  StackTrace:
	   at System.Runtime.CompilerServices.CastHelpers.Unbox(Void* toTypeHnd, Object obj)
	   at CommunityToolkit.Mvvm.Input.RelayCommand`1.CanExecute(Object parameter)
	   at MS.Internal.Commands.CommandHelpers.CanExecuteCommandSource(ICommandSource commandSource)
	   at System.Windows.Controls.Primitives.ButtonBase.UpdateCanExecute()
	   at System.Windows.Controls.Primitives.ButtonBase.HookCommand(ICommand command)
	   at System.Windows.Controls.Primitives.ButtonBase.OnCommandChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
	   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
	   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
	   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
	   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
	   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
	   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp)
	   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
	   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
	   at System.Windows.Data.BindingExpression.Activate(Object item)
	   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
	   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
	   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
	   at MS.Internal.Data.DataBindEngine.Run(Object arg)
	   at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
	   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
	   at System.Windows.ContextLayoutManager.UpdateLayout()
	   at System.Windows.UIElement.UpdateLayout()
	   at System.Windows.Interop.HwndSource.SetLayoutSize()
	   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
	   at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
	   at System.Windows.Window.SetRootVisual()
	   at System.Windows.Window.SetRootVisualAndUpdateSTC()
	   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
	   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
	   at System.Windows.Window.CreateSourceWindowDuringShow()
	   at System.Windows.Window.SafeCreateWindowDuringShow()
	   at System.Windows.Window.ShowHelper(Object booleanBox)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
	   at System.Windows.Threading.Dispatcher.Run()
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at System.Windows.Application.Run()
	   at RelayCommandStackTraceProblem.App.Main()

	  This exception was originally thrown at this call stack:
		[External Code]

### Steps to reproduce

```text
Run the attached example program.  

It will crash on load without allowing any user input.  

The line number of the incorrect code in c# or XAML is not provided, nor is any other diagnostic information that will assist in tracing the problem.
```

### Expected behavior

The line number in c# or XAML where the error occurs is provided in the stack trace and/or error message.  Diagnostic information such as the name of the command is helpful also.

### IDE and version

VS 2022

### IDE version

2022 17.2.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0-preview3

### Additional context

Same behavior in 7.1.2

[RelayCommandStackTraceProblem.zip](https://github.com/CommunityToolkit/dotnet/files/8791517/RelayCommandStackTraceProblem.zip)

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
> "Did you notice the subject of the ticket and the STR?"

I did, and I replied with an explanation as to why the UI stack invoked that method, causing the crash, before the user had a chance to enter any inputs. As I said, that's expected. A for there not being a line number, that's not an issue with the MVVM Toolkit, it's not like you'd normally be doing anything to specifically get a line number to be part of an exception.

That said, I guess we might want to change that exception type to be more helpful.
Maybe we should make it an `ArgumentException`, with that same message, or possibly with some additional info.
I guess that's reasonable, and technically more correct than throwing an `InvalidCastException.

**Comment by sam-wheat** [comment]
@Sergio0694 Your explanation is appreciated but it addresses a side-note of the ticket.

> That said, I guess we might want to change that exception type to be more helpful.

Ok, that may provide some insight to the developer. However it does not address the essence of this ask which is to **provide the line number of the offending code in the stack trace or error message be it XAML or C#**.

The example project has three buttons, one of which causes an exception to be raised.  Using the stack trace provided you cannot  identify which of the three buttons is the cause of the problem.  If this ticket is addressed as expected, the expectation is that the stack trace or error message will contain the line number of the button which causes the error to be raised.

Thanks for addressing this.

**Comment by michael-hawker** [comment]
@sam-wheat we can improve anything related to the cast error happening in the MVVM Toolkit, but for any of these types of errors that go through the UI stack, the underlying platform SDK need to provide better tooling/tracing to let you know which button was trying to update etc... and where that was created (XAML). There's nothing the MVVM Toolkit knows about that as the connection is made from the app layer and not the MVVM code itself.

This would be a good scenario to call out for the platform as well here: https://github.com/microsoft/microsoft-ui-xaml

**Comment by sam-wheat** [comment]
@michael-hawker  raise the issue in both repos?

**Comment by michael-hawker** [comment]
@sam-wheat since this stack trace is from WPF, filing there would be good too. I just know there's similar types of error messages which are hard to unwind in the newer stacks as well.
