### ISSUE TITLE
CanExecuteChanged is called internally on worker thread by AsyncRelayCommand

### ISSUE THREAD

**Issue by Shujee** [CommunityToolkit/dotnet#494]
### Describe the bug

When using MVVM Toolkit in a VSTO add-in containing WPF components, if you use `async`/`await` in an `AsyncRelayCommand` that is bound to a, say, `Button`, `await` does not return on the UI thread, which causes a cross-thread access exception. This is because Office applications (unlike normal WinForms and WPF apps) do not have a `SynchronizationContext` by default. This can be fixed by calling SetSynchronizationContext before calling an async function.

However, the problem is that `AsyncRelayCommand` appears to be calling `CanExecuteChanged()` internally at the end of command execution, which I don't know why executes on the worker thread, thereby throwing the cross-thread access exception (because the `Enabled` property of the `Button` is watching it, which requires it to run on UI thread). Since this call is internal, I do not have any way of executing it on the UI thread.

Interestingly, this does not happen if instead of using `Binding`, I call the command manually in the click event handler of the Button.

### Steps to reproduce

```text
1. Create a new VSTO project (.NET Framework 4.8, C#). I'm doing it for Outlook, but any Office should work. Add Community Toolkit's MVVM Nuget package to it.
2. Add a WPF control to the project
3. Add a WinForms Form and place an `ElementHost` onto it. Then put your WPF control inside the `ElementHost`.
4. Show the Form on the screen in addin's Startup event.
5. Write a VM class for the control. Inherit from `ObservableRecipient`. Add an `AsyncRelayCommand` to it.
6. Call an `async` function in your command with `await`.
7. Add a Button to your WPF control and bind it to your VM.
8. Run the application. When the form shows, click the button. Place a breakpoint in your command and see how the await line hits from the UI thread, but when the async method returns, it resumes on worker thread. Let the execution continue and you'll see the exception I mentioned.

I'll try to create a minimum reproducible version of the problem in the morning.
```

### Expected behavior

`CanExecuteChanged` should be called on the UI thread, because controls normally bind to it.

### IDE and version

VS 2022

### IDE version

Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.3.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Additional context

This is the exception message:

The calling thread cannot access this object because a different thread owns it.

This is the stack trace of the exception:

   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.Controls.Primitives.ButtonBase.get_Command()
   at System.Windows.Controls.Primitives.ButtonBase.UpdateCanExecute()
   at System.Windows.Controls.Primitives.ButtonBase.OnCanExecuteChanged(Object sender, EventArgs e)
   at System.Windows.Input.CanExecuteChangedEventManager.HandlerSink.OnCanExecuteChanged(Object sender, EventArgs e)
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.<<set_ExecutionTask>g__MonitorTask|26_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

### Help us help you

No, just wanted to report this

**Comment by jseddon2** [comment]
I have seen the same issue in a VSTO app using WPF.  For me, it occurs when a button is set as the default button and the command is triggered via the Enter key.  It doesn't occur if you just press the button.

@Shujee - did you find any solution?  I tried running the execute method on the UI thread but it didn't work, which would align with what you found that after the async task completes it is calling `CanExecuteChanged` not on the UI thread.

My workaround is just to handle the Enter key press event to call the command manually (which still requires a `Dispatcher.BeginInvoke()` to run it on the UI thread).
