### ISSUE TITLE
ObservableProperty breaks ExtractInterfaceCodeRefactoringProvider

### ISSUE THREAD

**Issue by mikeKuester** [CommunityToolkit/dotnet#726]
### Describe the bug

After adding the ObservableProperty attribute, the refactoring action "Extract Interface" throws an exception in Visual Studio 2022.

> "ExtractInterfaceCodeRefactoringProvider encountered an error and has been disabled."

```
System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.GetRequiredDocument(Solution solution,SyntaxTree syntaxTree)
   at async Microsoft.CodeAnalysis.Shared.Utilities.AnnotatedSymbolMapping.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ExtractInterface.AbstractExtractInterfaceService.ExtractInterfaceToNewFileAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ExtractInterface.AbstractExtractInterfaceService.ExtractInterfaceFromAnalyzedTypeAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ExtractInterface.ExtractInterfaceCodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorkerAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
```

### Steps to reproduce

Environment:
- .NET 7
- Visual Studio Enterprise 2022, v17.6.4
- WPF Application  template

Steps:
- Create a new project with the "WPF Application" template for C#.
- Add the Communmity.Toolkit.Mvvm package.
- Add a partial public class and inherit from ObservableObject.
- Add a private field with the attribute ObservableProperty.
- Right click on the class name and choose the refactoring action "Extract interface".

```csharp
public partial class ViewModel : ObservableObject
{
    [ObservableProperty]
    private int _myProperty;
}
```

Visual studio show the following error:

> "ExtractInterfaceCodeRefactoringProvider encountered an error and has been disabled."

```csharp
System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.GetRequiredDocument(Solution solution,SyntaxTree syntaxTree)
   at async Microsoft.CodeAnalysis.Shared.Utilities.AnnotatedSymbolMapping.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ExtractInterface.AbstractExtractInterfaceService.ExtractInterfaceToNewFileAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ExtractInterface.AbstractExtractInterfaceService.ExtractInterfaceFromAnalyzedTypeAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.ExtractInterface.ExtractInterfaceCodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorkerAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
```

### Expected behavior

The interface should be extracted from the class.

If I use this code - just with a public property with out using the ObservableProperty attribute, the interface could be extracted.

```csharp
public partial class ViewModel : ObservableObject
{
    public int MyProperty { get; set; }
}
```

### Screenshots

![image](https://github.com/CommunityToolkit/dotnet/assets/93646587/4545824c-9446-4b4a-83c1-494866c41cb5)

### IDE and version

VS 2022

### IDE version

17.6.4

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.2.0

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
@333fred this seems like it could just be an issue in the `ExtractInterfaceCodeRefactoringProvider` and not actually a bug in the MVVM Toolkit? Should we create a tracking issue for this in the Roslyn repo and just link back to this here? 🤔

**Comment by 333fred** [comment]
Yup, this is a roslyn bug.

**Comment by 333fred** [comment]
Yes

**Comment by mikeKuester** [comment]
I reported this to dotnet/roslyn, so this issue can be closed.
