### ISSUE TITLE
[BUG] MAUI Resizetizer file access issues on Windows build in Visual Studio in CommunityToolkit.Mvvm 8.2.2

### ISSUE THREAD

**Issue by SuperCorks** [CommunityToolkit/dotnet#882]
### Describe the bug

Recently I’ve been encountering this error with Resizetizer on build.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Access to the path 'C:\Milliman\DEVL\MOBILE\MAUI\Milliman.Benefits\Milliman.Benefits\obj\Debug\net8.0-android\resizetizer\r\drawable\settings.png' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at Microsoft.Maui.Resizetizer.ResizetizeImages.ExecuteAsync() in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 105
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()	Milliman.Benefits	C:\Users\simon\.nuget\packages\microsoft.maui.resizetizer\8.0.40\buildTransitive\Microsoft.Maui.Resizetizer.After.targets	631	
```

This error started occuring a few builds after I updated to 17.9.7. I also get this error with 17.10 preview 7.

If I run dotnet build from the terminal alone I still get this error, but if I run dotnet clean before the build works fine. In visual studio the build never works even if I clean before. I tried rolling back to 17.9.6 and I still get the issue.
See me reproducing the issue here: https://www.loom.com/share/8b4c17162bb54005a710a191a9e5d07c?sid=aede5d34-10f7-4f3c-ada2-29a17331b2e1

I also tried copying the project in another directory, same issue.

I'm also notiticing this only happens with .png files. Not svgs.

See sample project here: [test-issue.zip](https://github.com/CommunityToolkit/dotnet/files/15476898/test-issue.zip)

### Regression

8.0.0

### Steps to reproduce

```text
1. Open the project attached here.
2. Build for Android or iOS
```

### Expected behavior

Build's successfully in visual studio for windows.

### Screenshots

https://www.loom.com/share/8b4c17162bb54005a710a191a9e5d07c?sid=aede5d34-10f7-4f3c-ada2-29a17331b2e1

### IDE and version

VS 2022, VS 2022 Preview

### IDE version

17.9.6

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [ ] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.2.2

### Additional context

https://github.com/CommunityToolkit/Maui/issues/1907

https://developercommunity.visualstudio.com/t/MAUI---Resizetizer-files-access-to-the-p/10662058

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This seems unrelated to the MVVM Toolkit. You might want to report this issue in the MAUI repo.
